import requests
import warnings
import logging
from typing import Optional

# Suppress warnings for cleaner output
warnings.filterwarnings("ignore")
logging.getLogger("transformers").setLevel(logging.ERROR)


# ==============================
# Hugging Face API Assistant
# ==============================
class AdvancedFinanceLLMAssistant:
    """Advanced LLM Assistant using Hugging Face Inference API"""

    def __init__(self, hf_token: str):
        self.api_available = False
        self.fallback_mode = False
        self.hf_token = 'hf_token'
        self.setup_api()

    def setup_api(self):
        """Setup API connection and test availability"""
        if not self.hf_token or not self.hf_token.startswith("hf_"):
            print("⚠️ No valid Hugging Face token provided → using fallback mode")
            self.fallback_mode = True
            return

        self.api_available = True
        print("✅ Hugging Face API mode enabled")

    def _make_api_request(self, query: str, model: str) -> Optional[str]:
        """Make a request to Hugging Face Inference API"""
        try:
            url = f"https://api-inference.huggingface.co/models/{model}"
            headers = {
                "Authorization": f"Bearer {self.hf_token}",
                "Content-Type": "application/json"
            }
            payload = {
                "inputs": query,
                "parameters": {
                    "max_length": 200,
                    "temperature": 0.7,
                    "do_sample": True,
                    "top_p": 0.9,
                    "return_full_text": False
                }
            }

            response = requests.post(url, headers=headers, json=payload, timeout=15)
            if response.status_code == 200:
                print(f"✅ Response generated by API model: {model}")
                return response.json()[0].get('generated_text', '').strip()
            else:
                print(f"⚠️ API call failed for {model} (status {response.status_code})")
                return None

        except Exception as e:
            print(f"❌ API request error for {model}: {e}")
            return None

    def generate_response(self, user_query: str, budget_context: str = "") -> Optional[str]:
        """Generate a response using advanced LLM models"""
        if not self.api_available or self.fallback_mode:
            print("⚠️ API not available, skipping to fallback")
            return None

        try:
            prompt = self._create_financial_prompt(user_query, budget_context)
            models = [
                "meta-llama/Llama-2-7b-chat-hf",  # Strongest
                "microsoft/DialoGPT-medium",      # Medium
                "gpt2"                            # Weak fallback
            ]

            for model in models:
                response = self._make_api_request(prompt, model)
                if response and self._validate_response(response):
                    return self._clean_response(response)

            print("⚠️ All API models failed, using fallback")
            return None

        except Exception as e:
            print(f"❌ Error generating LLM response: {e}")
            return None

    def _create_financial_prompt(self, user_query: str, budget_context: str) -> str:
        return f"""You are a helpful and knowledgeable personal finance assistant.

Budget Context:
{budget_context}

User Question: {user_query}

Please provide a helpful, friendly, and accurate response about personal finance.
Keep it concise but informative.

Response:"""

    def _validate_response(self, response: str) -> bool:
        if not response or len(response.strip()) < 20:
            return False

        financial_keywords = [
            "money", "budget", "save", "invest", "debt", "income", "expense",
            "financial", "finance", "dollar", "cost", "price", "pay", "earn",
            "spend", "wealth", "retirement", "insurance", "credit", "loan"
        ]
        response_lower = response.lower()
        has_financial_content = any(k in response_lower for k in financial_keywords)

        bad_patterns = ["hack", "drunk", "pain in the ass", "ai but then"]
        has_bad_content = any(b in response_lower for b in bad_patterns)

        return has_financial_content and not has_bad_content

    def _clean_response(self, response: str) -> str:
        if "Response:" in response:
            response = response.split("Response:")[-1].strip()
        if "User Question:" in response:
            response = response.split("User Question:")[0].strip()
        if len(response) > 500:
            response = response[:500] + "..."
        return response.strip()


# ==============================
# Local Transformers Assistant
# ==============================
class LocalLLMAssistant:
    """Local LLM Assistant using transformers"""

    def __init__(self):
        self.model = None
        self.tokenizer = None
        self.model_loaded = False
        self.load_model()

    def load_model(self):
        """Load a local model"""
        try:
            model_name = "microsoft/DialoGPT-medium"
            print("⏳ Loading local AI model...")

            from transformers import AutoTokenizer, AutoModelForCausalLM
            self.tokenizer = AutoTokenizer.from_pretrained(model_name)
            self.model = AutoModelForCausalLM.from_pretrained(model_name)

            if self.tokenizer.pad_token is None:
                self.tokenizer.pad_token = self.tokenizer.eos_token

            self.model_loaded = True
            print("✅ Local AI model loaded:", model_name)

        except Exception as e:
            print(f"❌ Failed to load local model: {e}")
            self.model_loaded = False

    def generate_response(self, user_query: str, budget_context: str = "") -> Optional[str]:
        """Generate response using local model"""
        if not self.model_loaded:
            print("⚠️ Local model not loaded, skipping")
            return None

        try:
            import torch
            prompt = f"Financial Advisor: {user_query}\n\nBudget Info: {budget_context}\n\nResponse:"

            inputs = self.tokenizer.encode(prompt, return_tensors="pt", max_length=200, truncation=True)

            with torch.no_grad():
                outputs = self.model.generate(
                    inputs,
                    max_length=inputs.shape[1] + 150,
                    temperature=0.8,
                    do_sample=True,
                    top_p=0.9,
                    top_k=50,
                    repetition_penalty=1.2,
                    pad_token_id=self.tokenizer.eos_token_id,
                    eos_token_id=self.tokenizer.eos_token_id,
                    no_repeat_ngram_size=2
                )

            full_response = self.tokenizer.decode(outputs[0], skip_special_tokens=True)
            if "Response:" in full_response:
                response = full_response.split("Response:")[-1].strip()
            else:
                response = full_response.replace(prompt, "").strip()

            print("✅ Response generated by Local model")
            return response if len(response) > 20 else None

        except Exception as e:
            print(f"❌ Local model error: {e}")
            return None


    
    def _validate_response(self, response: str) -> bool:
        """Validate response quality"""
        if not response or len(response.strip()) < 20:
            return False
        
        # Check for financial relevance
        financial_keywords = [
            "money", "budget", "save", "invest", "debt", "income", "expense",
            "financial", "finance", "dollar", "cost", "price", "pay", "earn",
            "spend", "wealth", "retirement", "insurance", "credit", "loan"
        ]
        
        response_lower = response.lower()
        has_financial_content = any(keyword in response_lower for keyword in financial_keywords)
        
        # Check for inappropriate content
        bad_patterns = [
            "hack", "brain", "mind powers", "drunk", "games", "targets",
            "ai but then", "data there was", "move on", "pain in the ass"
        ]
        
        has_bad_content = any(pattern in response_lower for pattern in bad_patterns)
        
        return has_financial_content and not has_bad_content

# Keep the original rule-based assistant for fallback
class FinanceRuleBasedAssistant:
    """Enhanced rule-based assistant for when LLM is not available"""
    
    def __init__(self, budget_data, categories):
        self.budget_data = budget_data
        self.categories = categories
    
    def generate_response(self, user_query):
        """Generate response using rule-based system"""
        query = user_query.lower()
        
        # Enhanced pattern matching for better responses
        if any(word in query for word in ["save", "saving", "savings", "how to save"]):
            return self._get_savings_advice()
        elif any(word in query for word in ["invest", "investment", "investing", "stock", "stocks"]):
            return self._get_investment_advice()
        elif any(word in query for word in ["debt", "loan", "credit", "pay off", "payoff"]):
            return self._get_debt_advice()
        elif any(word in query for word in ["budget", "budgeting", "money management"]):
            return self._get_budgeting_advice()
        elif any(word in query for word in ["emergency", "fund", "reserve", "rainy day"]):
            return self._get_emergency_fund_advice()
        elif any(word in query for word in ["retirement", "pension", "401k", "ira", "retire"]):
            return self._get_retirement_advice()
        elif any(word in query for word in ["insurance", "coverage", "protect", "protection"]):
            return self._get_insurance_advice()
        elif any(word in query for word in ["tax", "taxes", "taxation", "deduction"]):
            return self._get_tax_advice()
        elif any(word in query for word in ["credit score", "credit card", "credit history"]):
            return self._get_credit_advice()
        elif any(word in query for word in ["real estate", "house", "home", "mortgage", "property"]):
            return self._get_real_estate_advice()
        elif any(word in query for word in ["cryptocurrency", "crypto", "bitcoin", "ethereum"]):
            return self._get_crypto_advice()
        elif any(word in query for word in ["side hustle", "freelance", "extra income", "part time"]):
            return self._get_side_income_advice()
        else:
            return self._get_general_financial_advice()
    
    def _get_savings_advice(self):
        return """💡 Savings Tips:
• Follow the 50/30/20 rule: 50% needs, 30% wants, 20% savings
• Set up automatic transfers to savings accounts
• Build an emergency fund covering 3-6 months of expenses
• Use high-yield savings accounts for better returns
• Track your savings progress monthly"""
    
    def _get_investment_advice(self):
        return """📈 Investment Basics:
• Start with low-cost index funds or ETFs
• Diversify your portfolio across different asset classes
• Consider your risk tolerance and time horizon
• Take advantage of employer 401(k) matching
• Regularly rebalance your portfolio
• Remember: time in market beats timing the market"""
    
    def _get_debt_advice(self):
        return """💳 Debt Management:
• Pay off high-interest debt first (credit cards)
• Consider debt consolidation if rates are lower
• Make more than minimum payments when possible
• Use the debt snowball or avalanche method
• Avoid taking on new debt while paying off existing debt
• Consider balance transfer cards for temporary relief"""
    
    def _get_budgeting_advice(self):
        return """📊 Budgeting Strategies:
• Track all income and expenses
• Use the envelope method for discretionary spending
• Review and adjust your budget monthly
• Set realistic goals and stick to them
• Use budgeting apps or spreadsheets
• Plan for irregular expenses (car maintenance, gifts)
• Build in some fun money to avoid feeling deprived"""
    
    def _get_emergency_fund_advice(self):
        return """🚨 Emergency Fund:
• Aim for 3-6 months of essential expenses
• Start small - even $500 can help with minor emergencies
• Keep it in a high-yield savings account
• Only use for true emergencies (job loss, medical bills)
• Replenish it after using it
• Consider a tiered approach: $1K, then 1 month, then 3-6 months"""
    
    def _get_retirement_advice(self):
        return """🏖️ Retirement Planning:
• Start early - compound interest is powerful
• Contribute to employer 401(k) up to the match
• Consider Roth vs Traditional based on your tax situation
• Aim to save 15% of income for retirement
• Increase contributions with raises
• Don't forget about IRAs and other retirement accounts
• Review and adjust your strategy as you age"""
    
    def _get_insurance_advice(self):
        return """🛡️ Insurance Essentials:
• Health insurance is a must-have
• Life insurance if others depend on your income
• Disability insurance protects your earning ability
• Home/renters insurance protects your assets
• Auto insurance is legally required
• Review coverage annually and shop around
• Consider umbrella insurance for additional protection"""
    
    def _get_tax_advice(self):
        return """📊 Tax Planning Tips:
• Keep detailed records of all income and expenses
• Maximize tax-advantaged accounts (401k, IRA, HSA)
• Consider tax-loss harvesting for investments
• Track deductible expenses (home office, business meals)
• Contribute to retirement accounts before year-end
• Consider Roth vs Traditional based on tax bracket
• Keep receipts for charitable donations
• Consult a tax professional for complex situations"""
    
    def _get_credit_advice(self):
        return """💳 Credit Score Improvement:
• Pay all bills on time (35% of score)
• Keep credit utilization below 30% (30% of score)
• Don't close old credit accounts
• Check your credit report regularly
• Avoid opening too many new accounts
• Consider becoming an authorized user
• Use credit cards responsibly
• Dispute any errors on your credit report"""
    
    def _get_real_estate_advice(self):
        return """🏠 Real Estate Investment:
• Save for a 20% down payment to avoid PMI
• Get pre-approved for a mortgage
• Consider location, schools, and future development
• Factor in all costs: taxes, insurance, maintenance
• Don't buy more house than you can afford
• Consider the 28/36 rule: 28% income for housing
• Research the neighborhood and market trends
• Get a thorough home inspection before buying"""
    
    def _get_crypto_advice(self):
        return """₿ Cryptocurrency Caution:
• Only invest what you can afford to lose
• Cryptocurrency is highly volatile and risky
• Diversify your investments beyond crypto
• Use reputable exchanges and wallets
• Be aware of tax implications
• Consider it a small portion of your portfolio
• Do thorough research before investing
• Be prepared for significant price swings"""
    
    def _get_side_income_advice(self):
        return """💼 Side Income Ideas:
• Freelance in your professional skills
• Start a small online business
• Offer tutoring or coaching services
• Rent out unused space or items
• Participate in the gig economy
• Create and sell digital products
• Offer consulting services
• Monetize a hobby or passion
• Remember to track income for taxes
• Don't overextend yourself - balance is key"""
    
    def _get_general_financial_advice(self):
        return """💰 General Financial Wellness:
• Live below your means
• Build good credit by paying bills on time
• Educate yourself about personal finance
• Set specific, measurable financial goals
• Review your finances regularly
• Don't try to keep up with others' spending
• Focus on building wealth, not just income
• Consider working with a financial advisor for complex situations
• Start investing early to benefit from compound interest
• Build an emergency fund before investing"""
